#!/bin/env python3
# spritesheetify
# author: Akritas Akritidis
# repo: https://github.com/MaanooAk/spritesheetify

# TODO implement trimming with the image box


from sys import exit, stderr
from argparse import ArgumentParser
from pathlib import Path


parser = ArgumentParser(
    description="Generate spritesheet"
)
parser.add_argument(
    "output",
    help="output spritesheet file prefix"
)
parser.add_argument(
    "inputs", nargs="+",
    help="sprite directories"
)
parser.add_argument(
    "-e", "--extrude", type=int, default=3,
    help="extrude size (default: 3)"
)
# parser.add_argument(
#     "-t", "--trim", action="store_true",
#     help="trim the transparency"
# )
parser.add_argument(
    "-m", "--max", type=int, default=4096,
    help="maximum size (default: 4096)"
)
parser.add_argument(
    "-f", "--force", "-B", action="store_true",
    help="force spritesheet generation"
)
parser.add_argument(
    "-s", "--script", type=str, default=".png.txt",
    help="extension for the script text files"
)

args = parser.parse_args()


def collect_paths(filenames):
    for filename in filenames:
        path = Path(filename)
        for i in path.rglob("*.png"):
            yield i
        for i in path.rglob("*.ora"):
            yield i
        for i in path.rglob("*" + args.script):
            yield i


def path_mod_time(path):
    stat = path.stat()
    return max(stat.st_mtime, stat.st_ctime)


output_info_path = Path(args.output + ".json")

if not args.force and output_info_path.exists():
    output_modified = output_info_path.stat().st_mtime
    sprites_modified = max(map(path_mod_time, collect_paths(args.inputs)))

    if sprites_modified < output_modified:
        exit(0)


# fmt: off
from collections import OrderedDict
from dataclasses import dataclass, asdict
from PIL import Image
from zipfile import ZipFile
from io import BytesIO
from xml.etree import ElementTree
from json import dumps
# fmt: on


def exit_code(code, message):
    print(message, file=stderr)
    exit(code)


@dataclass
class Sprite:
    path: Path = None
    name: str = None
    image: ImageFile = None
    size: (int, int) = None
    box_offset: (int, int) = None
    box_size: (int, int) = None
    sheet_id: int = None
    sheet_pos: (int, int) = None
    skip: bool = False


@dataclass
class Sheet:
    id: int
    size: (int, int) = (0, 0)
    line_offset: (int, int) = (0, 0)
    line_size: (int, int) = (0, 0)
    image: Image = None


def load_sprites_directory(filename):
    path = Path(filename)

    for i in path.rglob("*.png"):
        load_sprite_file(i)

    for i in path.rglob("*.ora"):
        load_sprite_ora(i)

    pending = []
    for i in path.rglob("*" + args.script):
        if load_sprite_meta(i) is False:
            pending.append(i)

    while len(pending) > 0:
        left = len(pending)
        pending = [i for i in pending if load_sprite_meta(i) is False]
        if left == len(pending):
            load_sprite_meta(pending[0], True)


def load_sprite_file(path):
    name = path.name.removesuffix(".png")
    image = Image.open(path)
    return load_sprite(path, name, image)


def load_sprite_ora(path):
    path_name = path.name.removesuffix(".ora")

    with ZipFile(path) as z:
        names = z.namelist()

        merged = Image.open(BytesIO(z.read("mergedimage.png")))
        load_sprite(path, path_name, merged)

        stack_data = z.read("stack.xml")
        root = ElementTree.fromstring(stack_data)
        size = (int(root.attrib.get("w")), int(root.attrib.get("h")))

        root_stack = root[0]
        layers = dict()

        for root_layer in reversed(root_stack):
            visible = root_layer.attrib.get("visibility") != "hidden"
            if not visible:
                continue

            name = root_layer.attrib.get("name")
            if name not in layers:
                layers[name] = Image.new("RGBA", size, (0, 0, 0, 0))

            load_sprite_ora_layers(z, layers[name], root_layer)

        for name, image in layers.items():
            load_sprite(path, path_name + "." + name, image)


def load_sprite_ora_layers(z, layer_image, element):
    visible = element.attrib.get("visibility") != "hidden"
    if not visible:
        return

    if element.tag == "stack":
        for i in reversed(element):
            load_sprite_ora_layers(z, layer_image, i)

    elif element.tag == "layer":
        src = element.attrib.get("src")
        image = Image.open(BytesIO(z.read(src)))
        offset = (
            int(element.attrib.get("x", "0")),
            int(element.attrib.get("y", "0")))

        layer_image.paste(image, offset, image)


def load_sprite_meta(path, last=False, id=None):
    name = path.name.removesuffix(args.script)
    image = None

    content = path.read_text()
    lines = content.split("\n")
    flags = None
    exports = []
    for line in lines:
        if len(line) == 0 or line[0] == "#":
            continue
        parts = line.split(" ")
        if parts[0] in ["mask", "m", "mask^", "m^"]:
            mask = int(parts[1])
            if parts[0].endswith("^"):
                mask = 1 << mask
            if id & mask == 0:
                continue
            parts = parts[2:]

        command, *params = parts
        if command in ["new", "clear"]:
            image = None
        elif command in ["source", "layer", "above", "top", "+", "below", "bottom"]:
            reference_name = params[0]
            source_sprite = sprites.get(reference_name)
            if source_sprite is None:
                if last:
                    return exit_code(1, f"Error: Sprite reference '{reference_name}' not found: {path}")
                return False
            if image is None:
                image = source_sprite.image.copy()
            else:
                if command in ["below", "bottom"]:
                    current = image
                    image = source_sprite.image.copy()
                    image.paste(current, (0, 0), current)
                else:
                    image.paste(source_sprite.image,
                                (0, 0), source_sprite.image)

        elif command == "rotate":
            if image is None:
                continue
            image = image.rotate(int(params[0]))
        elif command == "rotate+":
            if image is None:
                continue
            image = image.rotate(int(params[0]), expand=1)

        elif command == "resize":
            if image is None:
                continue
            if len(params) == 1:
                image = image.resize((int(params[0]), int(params[0])))
            else:
                w, h = int(params[0]), int(params[1])
                if h <= 0:
                    image = image.resize(
                        (w, int(image.size[1] * w / image.size[0])))
                elif w <= 0:
                    image = image.resize(
                        (int(image.size[0] * h / image.size[1]), h))
                else:
                    image = image.resize((w, h))

        elif command in ["translate", "move"]:
            if image is None:
                continue
            dx, dy = float(params[0]), float(params[1])
            dx = round(dx * image.size[0]) if "." in params[0] else dx
            dy = round(dy * image.size[1]) if "." in params[1] else dy
            image = image.transform(image.size, Image.AFFINE, (1, 0, -dx, 0, 1, -dy),
                                    resample=Image.BICUBIC, fillcolor=(0, 0, 0, 0))
        elif command in ["translate+", "move+"]:
            if image is None:
                continue
            dx, dy = float(params[0]), float(params[1])
            dx = round(dx * image.size[0]) if "." in params[0] else dx
            dy = round(dy * image.size[1]) if "." in params[1] else dy
            # TODO keep track of the image original origin
            new_size = (w + abs(dx), h + abs(dy))
            new_image = Image.new("RGBA", new_size, (0, 0, 0, 0))
            new_image.paste(image, (max(dx, 0), max(dy, 0)))
            image = new_image

        elif command in ["scale"]:
            if image is None:
                continue
            d = float(params[0])
            w = round(d * image.size[0]) if "." in params[0] else d
            h = round(d * image.size[1]) if "." in params[0] else d
            new_image = Image.new("RGBA", image.size, (0, 0, 0, 0))
            scaled = image.resize((w, h), resample=Image.BICUBIC)
            offset = (round((image.size[0] - w) / 2),
                      round((image.size[0] - h) / 2))
            new_image.paste(scaled, offset, scaled)
            image = new_image

        elif command == "nothing":
            image = Image.new("RGBA", (1, 1), (0, 0, 0, 0))

        elif command == "flags":
            if id is not None:
                continue
            flags = int(params[0])
            last_id = (1 << flags) - 1
            if load_sprite_meta(path, last, last_id) is False:
                return False
            for i in range(last_id):
                load_sprite_meta(path, last, i)
            return
        elif command in ["export", "save", "saveas"]:
            export_name = params[0]
            exports.append((export_name, image.copy()))

        else:
            return exit_code(1, f"Error: Unknown command '{command}': {path}")

    if image is None:
        image = Image.new("RGBA", (1, 1), (0, 0, 0, 0))

    for (export_name, export_image) in exports:
        load_sprite(path, export_name, export_image)

    if id is not None:
        name = name + "." + str(id)
    return load_sprite(path, name, image)


def load_sprite(path, name, image):
    sprite = Sprite()
    sprite.path = path
    sprite.name = name
    sprite.skip = False
    sprite.image = image
    sprite.size = image.size

    if name.startswith("."):
        sprite.name = name[1:]
        sprite.skip = True

    if "A" in image.getbands():
        alpha_box = image.split()[-1].getbbox()
        (left, upper, right, lower) = alpha_box or (
            0, 0, image.size[0], image.size[1])
        sprite.box_offset = (left, upper)
        sprite.box_size = (right-left, lower-upper)
    else:
        sprite.box_offset = (0, 0)
        sprite.box_size = image.size

    if name in sprites:
        return exit_code(1, f"Error: Duplicate name '{name}': {path}, {sprites[name].path}")

    sprites[sprite.name] = sprite


def pack(sprites, sheets):

    for sprite in sprites:
        if sprite.skip:
            continue
        for sheet in sheets:
            if pack_sprite(sprite, sheet):
                break
        if sprite.sheet_id is None:
            sheet = Sheet(len(sheets))
            sheets.append(sheet)
            pack_sprite(sprite, sheet)


def pack_sprite(sprite, sheet):
    e = args.extrude
    size = (sprite.size[0] + e*2, sprite.size[1] + e*2)

    if size[0] > args.max or size[1] > args.max:
        return exit_code(1, f"Sprite bigger than max size: {sprite.name}")

    h_space = args.max - sheet.line_offset[1]
    if h_space < size[1]:
        return False

    w_space = args.max - sheet.line_size[0]
    if w_space < size[0]:
        sheet.line_offset = (0, sheet.line_offset[1] + sheet.line_size[1])
        sheet.line_size = (0, 0)

    h_space = args.max - sheet.line_offset[1]
    if h_space < size[1]:
        return False

    sprite.sheet_id = sheet.id
    sprite.sheet_pos = (
        sheet.line_offset[0] + sheet.line_size[0] + e,
        sheet.line_offset[1] + e)
    sheet.line_size = (
        sheet.line_size[0] + size[0],
        max(sheet.line_size[1], size[1]))
    sheet.size = (max(sheet.size[0], sheet.line_size[0]),
                  sheet.line_offset[1] + sheet.line_size[1])

    return True


def generate(sprites, sheets):

    for sheet in sheets:
        image = Image.new("RGBA", sheet.size, (0, 0, 0, 0))

        for sprite in sprites:
            if sprite.sheet_id != sheet.id:
                continue
            x, y = sprite.sheet_pos
            w, h = sprite.size
            image.paste(sprite.image, (x, y))
            for e in range(args.extrude):
                image.paste(sprite.image.crop((0, 0, w, 1)), (x, y - e))
                image.paste(sprite.image.crop(
                    (0, h-1, w, h)), (x, y + h + e - 1))
                image.paste(sprite.image.crop((0, 0, 1, h)), (x-e, y))
                image.paste(sprite.image.crop(
                    (w-1, 0, w, h)), (x + w + e - 1, y))

        sheet.image = image
        sheet.image.save(f"{args.output}.{sheet.id}.png")


sprites = OrderedDict()

for input in args.inputs:
    load_sprites_directory(input)

sorted_sprites = sorted(sprites.values(), key=lambda sprite: (
    -sprite.size[1], -sprite.size[0], sprite.name
))

sheets = []
pack(sorted_sprites, sheets)
generate(sorted_sprites, sheets)

sprites_list = ",\n".join([
    dumps({
        "name": i.name,
        "sheet": i.sheet_id,
        "frame": {
            "x": i.sheet_pos[0],
            "y": i.sheet_pos[1],
            "w": i.size[0],
            "h": i.size[1],
        },
        "box": {
            "x": i.sheet_pos[0] + i.box_offset[0],
            "y": i.sheet_pos[1] + i.box_offset[1],
            "w": i.box_size[0],
            "h": i.box_size[1],
        },
    }, separators=(',', ':')) for i in sorted_sprites if not i.skip
])
document = f"""{{"sheets":{len(sheets)},"sprites":[\n{sprites_list}\n]}}"""

output_info_path.write_text(document)
